### ISSUE TITLE
When a file is removed should fileblocks also remove the reference from the block?

### ISSUE THREAD

**Issue by dougludlow** [rrharvey/grunt-file-blocks#15]
I have a block of scripts. When I add a javacript file, it is added to the block just as is expected. However, when I remove the javascript file, it is not removed fromthe block. Is this expected behavior?

**Comment by rrharvey** [comment]
The [removeFiles](https://github.com/rrharvey/grunt-file-blocks/wiki/Options) option should do that for you. It defaults to false.
