### ISSUE TITLE
Help can't understand documentation

### ISSUE THREAD

**Issue by GBora** [rrharvey/grunt-file-blocks#19]
Hello, I'm trying to use this plugin and I'm sure I've configured it wrongly but can't see how, first off in `index.html` where I need to insert the blocks I've added the following lines:

```
        <!-- fileblock:dev js-->
        <!-- endfileblock -->
        
        <!-- fileblock:dev app-->
        <!-- endfileblock  -->
```
And in my `Gruntfile.js` I've configured the plugin like so:
```
fileblocks: {
            dev: {
                files: [
                    {   src: 'index.html', 
                        options: {
                            removeAnchors: true,
                            rebuild: true
                        },
                        blocks: {
                            'js': { src: jsFiles},
                            'app': { src: angularFiles } 
                        } 
                    }
                ]
            }
        },
```
Where `jsFiles` and `angularFiles` are lists of my depencies respectively the files of my app, which I'd like to introduce into those two blocks, (I'm not using a regex because the structure of the files is too uneven)

Then running the command `grunt fileblocks` the output shows a sucess but none of the script tags are inserted.

**Comment by rrharvey** [comment]
You just have the template type and block name reversed in the comment. The part directly after the colon determines the type of template that will be used. In your case you want the JavaScript (js) template. [Replacement Blocks](https://github.com/rrharvey/grunt-file-blocks/wiki/Blocks)

    
    

    
    

Then your configuration would like like this:

```js
fileblocks: {
  dev: {
    files: [{
      src: 'index.html',
      options: {},
      blocks: {
        'blockName1': { src: [...file names...] },
        'blockName2': { src: [...file names...] }
      }
    }]
  }
}
````

and be run with

```console
$grunt fileblocks
```
_or_ 

```console
$grunt fileblocks:dev
```

**Comment by GBora** [comment]
@rrharvey Thank you, this solved the problem and now it works perfectly, thank you very much for writing this plugin.
