### ISSUE TITLE
Replacing with [object Object]

### ISSUE THREAD

**Issue by kaypro4** [rrharvey/grunt-file-blocks#20]
Hello, this is so close to being perfect for my use! I'm using it to load the contents of json translation files into my Angular app.js file to support angular-translate.

My grunt task is:
```
fileblocks: {
    options: {
        removeBlock: false,
        rebuild: true
    },
    locales: {
        src: 'assets/js/modules/app.js',
        blocks: {
        'en': { src: 'assets/locales/en.json'}
        }
    }
}
```

This is my app.js file before I run grunt fileblocks:locales:

```
$translateProvider.translations('en',
/* fileblock:raw en */
{}
/* endfileblock */
);
```

And here it is after:

```
$translateProvider.translations('en',
/* fileblock:raw en */
[object Object]
/* endfileblock */
);
```

Any idea how I would insert the actual content from the en.json file? Here it is:

```
{
  "calendar": "Calendar",
  "greeting": "partner",
  "report_unscheduled_activity": "Report Unscheduled Activity",
  "salutation": "Thanks!",
  "search": "Search",
  "timeline": "Timeline"
}

```

Thanks for any help!

**Comment by kaypro4** [comment]
Hello, @rrharvey any direction on this would be super appreciated. I've been really trying to get this to work but now I'm thinking maybe I'm misunderstanding what is possible with this plugin. I have tried a custom template but still haven't been able to get it to work. I'm out of ideas and this seems to be the only plugin that does anything close to what I'm looking for.

**Comment by rrharvey** [comment]
Sorry but that isn't going to work. The plugin doesn't read the contents of the file, only the file name. It was designed to insert script tags into HTML which only requires the file name. The fact that you were seeing [object Object] in your script file was actually a bug. Maybe that was misleading you into thinking that it was trying to insert the contents of the JSON file.
